/**
 * Generates src/instructions.ts from ai/mcp_prompt_firefly.md — pm/mcp.mdx §3.4, §8.3 (LOCKED).
 *
 *   node scripts/build-instructions.ts           write src/instructions.ts
 *   node scripts/build-instructions.ts --check   exit 1 if the checked-in file is stale
 *
 * The prompt lives at the REPO top level beside pm/, not inside mcp/. A build
 * that cannot find it FAILS — a server that ships an empty instructions block
 * has lost its whole routing defence — and so does an unknown {TOKEN}.
 *
 * FFMCP_BUILD_PROMPT / FFMCP_BUILD_OUT relocate the input / output (tests only).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { renderPrompt } from '../src/prompt-tokens.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const mcpRoot = path.resolve(here, '..');
const promptPath = process.env.FFMCP_BUILD_PROMPT ?? path.resolve(mcpRoot, '..', 'ai', 'mcp_prompt_firefly.md');
const outPath = process.env.FFMCP_BUILD_OUT ?? path.join(mcpRoot, 'src', 'instructions.ts');
const check = process.argv.includes('--check');

function die(message: string): never {
  process.stderr.write(`build-instructions: ${message}\n`);
  process.exit(1);
}

let source: string;
try {
  source = fs.readFileSync(promptPath, 'utf8');
} catch (err) {
  die(`cannot read the prompt ${promptPath} (${(err as NodeJS.ErrnoException).code ?? 'error'}) — the build FAILS rather than ship an empty instructions block`);
}
if (!source.trim()) die(`the prompt ${promptPath} is empty`);

const { text, unknown } = renderPrompt(source);
if (unknown.length) die(`unknown token(s) in ${path.basename(promptPath)}: ${[...new Set(unknown)].map((u) => `{${u}}`).join(', ')}`);

const generated = `// GENERATED by scripts/build-instructions.ts from ai/mcp_prompt_firefly.md — DO NOT EDIT.
// Edit the prompt, then \`just build\`. test/instructions.test.ts fails when this file is stale.
import { resolvePrompt } from './prompt.js';

export const INSTRUCTIONS: string = ${JSON.stringify(text)};

/** The instructions sent at initialize: the constant, or FFMCP_PROMPT_FILE's text (§8.3). */
export function resolveInstructions(promptFile: string | undefined, warn: (message: string) => void): string {
  return resolvePrompt(INSTRUCTIONS, promptFile, warn);
}
`;

if (check) {
  let current = '';
  try {
    current = fs.readFileSync(outPath, 'utf8');
  } catch {
    /* missing counts as stale */
  }
  if (current !== generated) die(`${path.relative(mcpRoot, outPath)} is stale — run: node scripts/build-instructions.ts`);
  process.stderr.write('build-instructions: up to date\n');
  process.exit(0);
}

fs.writeFileSync(outPath, generated, 'utf8');
process.stderr.write(`build-instructions: wrote ${path.relative(mcpRoot, outPath)} (${text.length} chars)\n`);
